/* Episode data for all seasons */
const EPISODES = [
  { season:1, ep:1,  title:'К тебе, спустя две тысячи лет: Падение Сигансины, ч. 1' },
  { season:1, ep:2,  title:'Тот день: Падение Сигансины, ч. 2' },
  { season:1, ep:3,  title:'Тусклый проблеск среди отчаянья: Возвращение человечества, ч. 1' },
  { season:1, ep:4,  title:'Ночь выпуска: Возвращение человечества, ч. 2' },
  { season:1, ep:5,  title:'Первое сражение: Оборона Троста, ч. 1' },
  { season:1, ep:6,  title:'Мир глазами девочки: Оборона Троста, ч. 2' },
  { season:1, ep:7,  title:'Маленький клинок: Оборона Троста, ч. 3' },
  { season:1, ep:8,  title:'Слышно биение сердца: Оборона Троста, ч. 4' },
  { season:1, ep:9,  title:'Случай с левой рукой: Оборона Троста, ч. 5' },
  { season:1, ep:10, title:'Ответ: Оборона Троста, ч. 6' },
  { season:1, ep:11, title:'Идол: Оборона Троста, ч. 7' },
  { season:1, ep:12, title:'Рана: Оборона Троста, ч. 8' },
  { season:1, ep:13, title:'Сокровенное желание: Оборона Троста, ч. 9' },
  { season:1, ep:14, title:'Не могу посмотреть ему в глаза: Подготовка к контратаке, ч. 1' },
  { season:1, ep:15, title:'Отряд специального назначения: Подготовка к контратаке, ч. 2' },
  { season:1, ep:16, title:'Что нужно сделать сейчас: Накануне контрнаступления, ч. 3' },
  { season:1, ep:17, title:'Женская особь' },
  { season:1, ep:18, title:'Лес гигантских деревьев' },
  { season:1, ep:19, title:'Укус' },
  { season:1, ep:20, title:'Эрвин Смит' },
  { season:1, ep:21, title:'Железный молот' },
  { season:1, ep:22, title:'Побеждённые: 57-я экспедиция за стены, ч. 6' },
  { season:1, ep:23, title:'Улыбка: Рейд в район Стохэсс, ч. 1' },
  { season:1, ep:24, title:'Помилование: Рейд в район Стохэсс, ч. 2' },
  { season:1, ep:25, title:'Стена: Рейд в район Стохэсс, ч. 3' },

  { season:2, ep:1,  title:'Звероподобный титан' },
  { season:2, ep:2,  title:'Я дома' },
  { season:2, ep:3,  title:'На юго-запад' },
  { season:2, ep:4,  title:'Солдат' },
  { season:2, ep:5,  title:'Хистория' },
  { season:2, ep:6,  title:'Воин' },
  { season:2, ep:7,  title:'Ближний бой' },
  { season:2, ep:8,  title:'Охотники' },
  { season:2, ep:9,  title:'Открытие' },
  { season:2, ep:10, title:'Дети' },
  { season:2, ep:11, title:'Зарядка' },
  { season:2, ep:12, title:'Крик' },

  { season:3, ep:1,  title:'Сигнальный огонь' },
  { season:3, ep:2,  title:'Боль' },
  { season:3, ep:3,  title:'Старая история' },
  { season:3, ep:4,  title:'Доверие' },
  { season:3, ep:5,  title:'Ответ' },
  { season:3, ep:6,  title:'Грех' },
  { season:3, ep:7,  title:'Желание' },
  { season:3, ep:8,  title:'За стенами района Орвуд' },
  { season:3, ep:9,  title:'Правитель стен' },
  { season:3, ep:10, title:'Друзья' },
  { season:3, ep:11, title:'Наблюдатель' },
  { season:3, ep:12, title:'Ночь перед контрнаступлением' },
  { season:3, ep:13, title:'Город, в котором всё началось' },
  { season:3, ep:14, title:'Громовые копья' },
  { season:3, ep:15, title:'Спуск' },
  { season:3, ep:16, title:'Идеальная игра' },
  { season:3, ep:17, title:'Герой' },
  { season:3, ep:18, title:'Полуночное солнце' },
  { season:3, ep:19, title:'Подвал' },
  { season:3, ep:20, title:'В тот день' },
  { season:3, ep:21, title:'Атакующий титан' },
  { season:3, ep:22, title:'По ту сторону стены' },

  { season:4, ep:1,  title:'По ту сторону океана' },
  { season:4, ep:2,  title:'Полуночный поезд' },
  { season:4, ep:3,  title:'Врата надежды' },
  { season:4, ep:4,  title:'Из рук в руки' },
  { season:4, ep:5,  title:'Объявление войны' },
  { season:4, ep:6,  title:'Титан Молотобоец' },
  { season:4, ep:7,  title:'Нападение' },
  { season:4, ep:8,  title:'Пуля убийцы' },
  { season:4, ep:9,  title:'Добровольцы' },
  { season:4, ep:10, title:'Справедливый довод' },
  { season:4, ep:11, title:'Притворщики' },
  { season:4, ep:12, title:'Лидер' },
  { season:4, ep:13, title:'Дети леса' },
  { season:4, ep:14, title:'Жестокость' },
  { season:4, ep:15, title:'Единственное спасение' },
  { season:4, ep:16, title:'Небеса и земля' },
  { season:4, ep:17, title:'Суждение' },
  { season:4, ep:18, title:'Неожиданный удар' },
  { season:4, ep:19, title:'Братья' },
  { season:4, ep:20, title:'Воспоминания о будущем' },
  { season:4, ep:21, title:'За две тысячи лет до тебя' },
  { season:4, ep:22, title:'Оттепель' },
  { season:4, ep:23, title:'Закат' },
  { season:4, ep:24, title:'Достоинство' },
  { season:4, ep:25, title:'Ночь конца' },
  { season:4, ep:26, title:'Предатель' },
  { season:4, ep:27, title:'Ретроспектива' },
  { season:4, ep:28, title:'Рассвет человечества' },
  { season:4, ep:29, title:'Гул Земли / Грешники' },
  { season:4, ep:30, title:'Финальный сезон: Битва неба и земли / Длинный сон' },
];
